### ISSUE TITLE
Get Discord server invite link

### ISSUE THREAD

**Issue by antoninhrlt** [sflk-lang/sflk#4]
Hey,
I'm looking for the SFLK Discord, and I found that on the README.md :
> Note that there is a Discord server dedicated to the development and use of SFLK (how to get in there? we don't know haha, maybe ask for an invite in one way or another).

Is this the good place to get the invite ?
Anyway, I would like to get it :)
Thanks

**Comment by anima-libera** [comment]
Oh wow yes sure
https://discord.gg/7WD7WaHR

It will be a good occasion to get this project moving again ^^
